authorization:
  ds:
    uri: mongodb+srv://root:root@cluster0-68qwp.mongodb.net/authorization?retryWrites=true&w=majority&connectTimeoutMS=300000&minPoolSize=1&maxPoolSize=10&maxIdleTimeMS=900000

logging:
  level:
    org:
      springframework: INFO